source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "cucumber"

gem "rspec"
gem "rspec-example_steps"
gem "rspec-wait"

gem "capybara"
gem "capybara-inline-screenshot"
gem "selenium-webdriver"
gem "thin"
gem "webdrivers"

gem "pry"
gem "pry-byebug"
gem "pry-stack_explorer"

gem "rubocop"
